// question
export const QUESTIONS_GET_ACTION = 'QUESTIONS_GET'
export const QUESTION_GET_ACTION = 'QUESTION_GET'
export const QUESTION_SCORE_UPDATE_ACTION = 'QUESTION_SCORE_UPDATE'

// tag
export const TAGS_GET_ACTION = 'TAGS_GET'

// answer
export const ANSWERS_FOR_QUESTION_GET_ACTION = 'ANSWERS_FOR_QUESTION_GET'
export const ANSWER_ADD_ACTION = 'QUESTION_ADD'
export const ANSWER_SCORE_UPDATE_ACTION = 'ANSWER_SCORE_UPDATE'

// user
export const USER_GET_ACTION = 'USER_GET'
