// question
export const QUESTIONS_SET_MUTATION = 'QUESTIONS_SET'
export const QUESTION_SET_MUTATION = 'QUESTION_SET'
export const QUESTIONS_SET_TOTAL_MUTATION = 'QUESTIONS_SET_TOTAL'

// tag
export const TAGS_SET_MUTATION = 'TAGS_SET'

// answer
export const ANSWERS_SET_MUTATION = 'ANSWER_SET'
